### STEP: 1

Import necessary libraries for **Predicting Future Stock Prices**

In [114]:
# Import required libraries
import numpy as np
import pandas as pd
import hvplot.pandas
import requests

import warnings
warnings.filterwarnings('ignore')

# Libraries to Extract Stock Price Historical Data 
# from Yahoo! Finance using Tickers from Wikipedia
import yfinance as yf
from pandas.tseries.offsets import DateOffset
from datetime import datetime, timedelta
from pandas.tseries.holiday import USFederalHolidayCalendar

# Library for Technical Analysis
import pandas_ta as ta

# Libraries for ML Analysis using Linear Models
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import MultiTaskElasticNet
from sklearn.linear_model import LassoLars
from sklearn.linear_model import BayesianRidge

scaler = StandardScaler()
today = datetime.today().strftime('%Y-%m-%d')

### STEP: 2

Defining various functions used in the code for 
* extracting data, 
* adding technical indicators as features,
* predicting **Close** price and **VWAP** volume-weighted average price,
* using linear models for predicting with best model output.

Best model is selected based on minimum MAPE & RMSE

In [115]:
# Extracting Stock Price Historical Data from Yahoo! Finance using Tickers from Wikipedia
        
def extract_stock_data(stock_name, start_date):
    row_index = ticker_df.query(f"Security == '{stock_name}'").index[0]
    stock_ticker = ticker_list[row_index]
    OHLCV_df = yf.download(stock_ticker,start_date,today)
    OHLCV_df.index = pd.to_datetime(OHLCV_df.index)
    #print(f"{stock_ticker}:{stock_name}")
    #display(OHLCV_df.head(3))
    #display(OHLCV_df.tail(3))
    return(OHLCV_df)

# Feature Engineering _ additionals features for ML Analysis

def technical_indicators():
    OHLCV_df = extract_stock_data(stock_name, start_date)
    # VWAP modified to use Annual cummulative sum
    OHLCV_df['typical_price'] = (OHLCV_df['High']+OHLCV_df['Low']+OHLCV_df['Close'])/3
    OHLCV_df['vw_typical_price'] = OHLCV_df['typical_price']*OHLCV_df['Volume']
    OHLCV_df['vwap_annual'] = OHLCV_df.groupby(OHLCV_df.index.year)['vw_typical_price'].cumsum() / OHLCV_df.groupby(OHLCV_df.index.year)['Volume'].cumsum()
    # Daily Returns
    OHLCV_df['daily_returns'] = OHLCV_df['Close'].pct_change()
    # 21Day Volatility
    OHLCV_df['volatility_21'] = OHLCV_df['Close'].rolling(window=21).std()
    # Simple Moving Avg 21Days & 50Days
    OHLCV_df['sma_21'] = OHLCV_df.ta.sma(length=21)
    OHLCV_df['sma_50'] = OHLCV_df.ta.sma(length=50)
    # Exponential Moving Avg 21Days & 50Days
    OHLCV_df['ema_21'] = OHLCV_df.ta.ema(length=21)
    OHLCV_df['ema_50'] = OHLCV_df.ta.ema(length=50)
    # RSI Momemtum Indicator 14Days
    rsi_df = OHLCV_df.ta.rsi()
    # MACD Momentum Indicator
    macd_df = OHLCV_df.ta.macd()
    # Bolinger Bands %B Indicator
    bbands_df = OHLCV_df.ta.bbands()
    # On-Balance Volume in Millions
    # OHLCV_df['OBV_in_million'] = OHLCV_df.ta.obv()/1000000
    # Average Directional Index 14Days
    # adx_df = OHLCV_df.ta.adx()
    # Dropping trivial Columns
    OHLCV_append_df = pd.concat([OHLCV_df,rsi_df,macd_df,bbands_df],axis=1).drop(
        columns = ['Open','High','Low','Adj Close','Volume',
                   'typical_price','vw_typical_price']).dropna()
    #display(OHLCV_append_df.tail())
    
    return(OHLCV_append_df)

In [116]:
# Predicting Stock Close & Volume-Weighted Average Price(VWAP) using Linear Models

def predict_close_vwap():
    # Next Day's "Close" as target
    predictors_df = technical_indicators()
    target_close_df = predictors_df[['Close']].shift(-1)
    target_vwap_df = predictors_df[['vwap_annual']].shift(-1)

    # Training Data of 27months and Testing Data of 6months alternatively 
    # with latest 33months of testing data
    train_range_months = 11
    test_range_months = 22
    split_range = list(range(len(predictors_df)//21//(train_range_months+test_range_months)))
    predictors_train = pd.DataFrame()
    
    for i in split_range:
        train_df = predictors_df.iloc[21*33*i:(21*33*i)+(21*(33-test_range_months)),:]
        predictors_train = pd.concat([predictors_train,train_df],axis=0)
        
    predictors_test = predictors_df.drop(index = predictors_train.index)
    target_train_close = target_close_df.drop(index = predictors_test.index)
    target_test_close = target_close_df.drop(index = predictors_train.index)
    target_train_vwap = target_vwap_df.drop(index = predictors_test.index)
    target_test_vwap = target_vwap_df.drop(index = predictors_train.index)
    
    #Using StandardScaler to fit predictors train data and transform both train and test data 
    predictors_scaled = scaler.fit(predictors_train)
    predictors_train_scaled = predictors_scaled.transform(predictors_train)
    predictors_test_scaled = predictors_scaled.transform(predictors_test)

    list_of_models = [Ridge(),Lasso(),MultiTaskElasticNet(),
                  LassoLars(),BayesianRidge()]
    target_predictions_close_df = target_test_close.copy()
    for model in list_of_models:
        model_instance_close = model
        model_instance_close.fit(predictors_train_scaled,target_train_close)
        model_prediction_close = model_instance_close.predict(predictors_test_scaled)
        target_predictions_close_df[f'{model}_Close'] = model_prediction_close

    target_predictions_vwap_df = target_test_vwap.copy()
    for model in list_of_models:
        model_instance_vwap = model
        model_instance_vwap.fit(predictors_train_scaled,target_train_vwap)
        model_prediction_vwap = model_instance_vwap.predict(predictors_test_scaled)
        target_predictions_vwap_df[f'{model}_vwap_annual'] = model_prediction_vwap

    target_predictions_df = pd.concat([target_predictions_close_df,target_predictions_vwap_df],axis=1)

    #display(target_predictions_df.tail())
    #display(target_predictions_close_df.hvplot(frame_width=500,frame_height=300))
    return(target_predictions_close_df,target_predictions_vwap_df,target_predictions_df)

In [117]:
# Calculating Root_Mean_Square_Error(RMSE) 
# and Mean_Absolute_Percentage_Error(MAPE)

def linear_model_predictions():
    #display(extract_stock_data(stock_name, start_date).head(3))
    #display(extract_stock_data(stock_name, start_date).tail(3))
    #display(technical_indicators().tail())
    target_close_predictions_df,target_vwap_predictions_df,target_predictions_df = predict_close_vwap()
    column_range_close = list(target_close_predictions_df.columns)
    column_range_vwap = list(target_vwap_predictions_df.columns)
    dict_close = {}
    dict_vwap = {}
    for i in column_range_close[1:]:
        rmse_close = np.sqrt(np.mean(
            (target_predictions_df.loc[:today,'Close']-target_predictions_df.loc[:today,i])**2))
        mape_close = np.mean(np.abs(
            (target_predictions_df.loc[:today,'Close']-target_predictions_df.loc[:today,i])/target_predictions_df.loc[:today,'Close']))*100
        dict_close[f'{i}'] = [rmse_close,mape_close]
    for i in column_range_vwap[1:]:  
        rmse_vwap = np.sqrt(np.mean(
            (target_predictions_df.loc[:today,'vwap_annual']-target_predictions_df.loc[:today,i])**2))
        mape_vwap = np.mean(np.abs(
            (target_predictions_df.loc[:today,'vwap_annual']-target_predictions_df.loc[:today,i])/target_predictions_df.loc[:today,'vwap_annual']))*100
        dict_vwap[f'{i}'] = [rmse_vwap,mape_vwap]
    error_measures_close = pd.DataFrame.from_dict(dict_close, orient = 'index', columns = ['RMSE_close','MAPE_close'])
    error_measures_vwap = pd.DataFrame.from_dict(dict_vwap, orient = 'index', columns = ['RMSE_vwap','MAPE_vwap'])
    error_measures_close = error_measures_close.sort_values(by=['MAPE_close'])
    error_measures_vwap = error_measures_vwap.sort_values(by=['MAPE_vwap'])

    #display(error_measures_close)
    #display(error_measures_close.hvplot.bar(rot=90,frame_width=500,frame_height=300))
    
    #Choosing model with lowest MAPE value
    best_estimate_close = error_measures_close.index[0]
    best_estimate_vwap = error_measures_vwap.index[0]

    predictions_output = target_predictions_df[['Close','vwap_annual',best_estimate_close, best_estimate_vwap]]
    
    nxt_day = predictions_output.index[-1]+pd.Timedelta(days=1)
    #Checking for Federal Holidays
    cal = USFederalHolidayCalendar()
    holidays = pd.to_datetime(cal.holidays(today, '2024-12-31'))
    hol = list(holidays)
    for i in hol:
        if nxt_day==i:
            nxt_day = nxt_day+pd.Timedelta(days=1)
    #Checking for Weekends
    if nxt_day.weekday()==5:
        nxt_day = nxt_day+pd.Timedelta(days=2)
    elif nxt_day.weekday()==6:
        nxt_day = nxt_day+pd.Timedelta(days=1)
    else:
        nxt_day = nxt_day
    
    predictions_output.loc[nxt_day] = np.nan
    predictions_output = predictions_output.shift()
    predictions_output['Close']=predictions_output['Close'].fillna(predictions_output[best_estimate_close])
    predictions_output['vwap_annual']=predictions_output['vwap_annual'].fillna(predictions_output[best_estimate_vwap])
    #Output Last 30(252*2.5) Months Data
    predictions = predictions_output[['Close','vwap_annual']].iloc[-504:]
    best_model = error_measures_close.iloc[0,:]
    comparison_plot = predictions_output[['Close',best_estimate_close]].loc['2024':today].hvplot(frame_width=500,frame_height=300) 
    
    return (best_model,predictions)

In [118]:
# Feature Engineering _ for future prediction using stock_predictions as input
# OBV & ADX dropped to limit predicted features

def feature_engineering(df):
    # Daily Returns
    df['daily_returns'] = df['Close'].pct_change()
    # 21Day Volatility
    df['volatility_21'] = df['Close'].rolling(window=21).std()
    # Simple Moving Avg 21Days & 50Days
    df['sma_21'] = df['Close'].rolling(window=21).mean()
    df['sma_50'] = df['Close'].rolling(window=50).mean()
    # Exponential Moving Avg 21Days & 50Days
    df['ema_21'] = df['Close'].ewm(span=21, adjust=False).mean()
    df['ema_50'] = df['Close'].ewm(span=50, adjust=False).mean()
    # RSI Momemtum Indicator 14Days
    rsi_df = df.ta.rsi()
    # MACD Indicator
    macd_df = df.ta.macd()
    # Bolinger Bands %B Indicator
    bbands_df = df.ta.bbands()
    # Dropping trivial Columns
    append_df = pd.concat([df,rsi_df,macd_df,bbands_df],axis=1).dropna()
    # trim_df = df[['Close','vwap_annual']]
    return(append_df)

In [119]:
# Creating instance of best fit model _ BayesianRidge()
# By fitting the historical data

def best_fit_model_future_prediction(df):
    # Next Day's "Close" as target
    predictors_df = technical_indicators()
    #predictors_df = predictors_df.drop(columns=['Volume','ADX_14'])
    target_close_df = predictors_df[['Close']].shift(-1)
    target_vwap_df = predictors_df[['vwap_annual']].shift(-1)

    predictors_future_df = feature_engineering(df)
    display(predictors_future_df.head(1))
    display(predictors_future_df.tail(1))
    target_future_close_df = predictors_future_df[['Close']].shift(-1)
    target_future_vwap_df = predictors_future_df[['vwap_annual']].shift(-1)

    # Training Data of 27months and Testing Data of 6months alternatively 
    # with latest 33months of testing data
    train_range_months = 11
    test_range_months = 22
    split_range = list(range(len(predictors_df)//21//(train_range_months+test_range_months)))
    predictors_train = pd.DataFrame()
    
    for i in split_range:
        train_df = predictors_df.iloc[21*33*i:(21*33*i)+(21*(33-test_range_months)),:]
        predictors_train = pd.concat([predictors_train,train_df],axis=0)
        
    predictors_test = predictors_df.drop(index = predictors_train.index)
    target_train_close = target_close_df.drop(index = predictors_test.index)
    target_test_close = target_close_df.drop(index = predictors_train.index)
    target_train_vwap = target_vwap_df.drop(index = predictors_test.index)
    target_test_vwap = target_vwap_df.drop(index = predictors_train.index)
    
    #Using StandardScaler to fit predictors train data and transform both train and test data 
    predictors_scaled = scaler.fit(predictors_train)
    predictors_train_scaled = predictors_scaled.transform(predictors_train)
    predictors_future_scaled = predictors_scaled.transform(predictors_future_df)

    best_model = BayesianRidge()
    target_future_close = target_future_close_df.copy()
    model_instance_close = best_model
    model_instance_close.fit(predictors_train_scaled,target_train_close)
    model_prediction_close = model_instance_close.predict(predictors_future_scaled)
    target_future_close[f'{best_model}_Close'] = model_prediction_close[-1]

    target_future_vwap = target_future_vwap_df.copy()
    model_instance_vwap = best_model
    model_instance_vwap.fit(predictors_train_scaled,target_train_vwap)
    model_prediction_vwap = model_instance_vwap.predict(predictors_future_scaled)
    target_future_vwap[f'{best_model}_vwap_annual'] = model_prediction_vwap[-1]

    target_future_df = pd.concat([target_future_close,target_future_vwap],axis=1)

    #display(target_future_df.tail(1))

    nxt_day = target_future_df.index[-1]+pd.Timedelta(days=1)
    #Checking for Federal Holidays
    cal = USFederalHolidayCalendar()
    holidays = pd.to_datetime(cal.holidays(today, '2024-12-31'))
    hol = list(holidays)
    for i in hol:
        if nxt_day==i:
            nxt_day = nxt_day+pd.Timedelta(days=1)
    #Checking for Weekends
    if nxt_day.weekday()==5:
        nxt_day = nxt_day+pd.Timedelta(days=2)
    elif nxt_day.weekday()==6:
        nxt_day = nxt_day+pd.Timedelta(days=1)
    else:
        nxt_day = nxt_day
    
    target_future_df.loc[nxt_day] = np.nan
    target_future_df = target_future_df.shift()
    target_future_df['Close']=target_future_df['Close'].fillna(target_future_df[f'{best_model}_Close'])
    target_future_df['vwap_annual']=target_future_df['vwap_annual'].fillna(target_future_df[f'{best_model}_vwap_annual'])
    #Output Last 30Months Data
    predictions = target_future_df[['Close','vwap_annual']].iloc[-504:]
    return (predictions)

In [120]:
# Scrapping for List of stocks in S&P500 for Linear Model ML Prediction Analysis
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
  
wiki_data = pd.read_html(url)

ticker_df = wiki_data[0]
display(ticker_df.head(2))
display(ticker_df.tail(2))

# Pick Stock from the list for analysis

ticker_list= ticker_df['Symbol'].to_list()
stock_list = ticker_df['Security'].to_list()
#print(stock_list)
#stock_name = input('Enter Stock_Name from the above displayed list for Analysis:')
#start_date = input('Enter Start Date for Historical Data in yyyy-mm-dd:')

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [ ]:
# display predictions
master_df=pd.DataFrame()
model_df=pd.DataFrame()

for stock in stock_list[3:]:
    stock_name = stock
    start_date = '2012-01-01'

    model,stock_predictions = linear_model_predictions()
    future_stock_price = best_fit_model_future_prediction(stock_predictions)
    # Predicting Stocks on Future Dates _ Next 14 Days
    for i in list(range(1,14)):
        future_stock_price = best_fit_model_future_prediction(future_stock_price)
        
    master_df[f'{stock}_close'] = future_stock_price['Close']
    model_df['Stock']=stock_name
    model_df['RMSE']= model[0]
    model_df['MAPE']=model[1]

In [121]:
stock_name='3M'
start_date='2013-01-01'
raw_df=extract_stock_data('3M','2013-01-01')
raw_df.head()

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close   Volume
Date
2013-01-02  94.190002  94.790001  93.959999  94.779999  65.751122  3206700
2013-01-03  94.339996  94.930000  94.129997  94.669998  65.674805  2704600
2013-01-04  94.790001  95.480003  94.540001  95.370003  66.160439  2704900
2013-01-07  95.019997  95.730003  94.760002  95.489998  66.243668  2745800
2013-01-08  95.169998  95.750000  95.099998  95.500000  66.250603  2655500

In [122]:
df1=technical_indicators()
df1.head()

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2013-03-14,106.019997,100.864709,0.008850,1.188187,103.930952,101.1418,103.912855,101.141800,66.830226,1.314123,-0.016291,1.330414,104.802554,105.551997,106.301440,1.420045,0.812231
2013-03-15,106.400002,101.068221,0.003584,1.276485,104.099523,101.3742,104.138959,101.348004,68.388842,1.349696,0.015425,1.334271,104.669799,105.689998,106.710197,1.930549,0.847973
2013-03-18,105.410004,101.125439,-0.009304,1.269549,104.224762,101.5890,104.254509,101.507298,60.423048,1.283211,-0.040848,1.324059,104.577331,105.609999,106.642667,1.955626,0.403166
2013-03-19,105.180000,101.217498,-0.002182,1.264456,104.317619,101.7852,104.338644,101.651325,58.712026,1.198150,-0.100727,1.298877,104.605307,105.620000,106.634692,1.921403,0.283186
2013-03-20,105.660004,101.273098,0.004564,1.297223,104.388095,101.9886,104.458768,101.808528,61.182473,1.156144,-0.114186,1.270330,104.865570,105.734001,106.602433,1.642672,0.457396

In [123]:
df2,df3,df4=predict_close_vwap()

display(df4)

[*********************100%%**********************]  1 of 1 completed

,Close,Ridge()_Close,Lasso()_Close,MultiTaskElasticNet()_Close,LassoLars()_Close,BayesianRidge()_Close,vwap_annual,Ridge()_vwap_annual,Lasso()_vwap_annual,MultiTaskElasticNet()_vwap_annual,LassoLars()_vwap_annual,BayesianRidge()_vwap_annual
Date,,,,,,,,,,,,
2014-02-12,130.139999,130.199563,131.616273,132.964091,131.616273,130.252816,132.107316,131.897481,133.047261,132.213365,133.036131,131.867875
2014-02-13,132.119995,130.018680,131.327677,132.768714,131.327677,130.084729,132.081423,131.827419,132.975989,131.872912,132.964963,131.758526
2014-02-14,131.800003,132.520317,133.232387,134.594434,133.232387,132.189566,132.080907,131.936927,132.951328,131.888091,132.940332,131.930883
2014-02-18,130.559998,131.801403,132.924562,134.191227,132.924562,131.770713,132.058917,131.884833,132.951021,131.728576,132.939996,131.931932
2014-02-19,131.559998,130.501480,131.731706,133.204980,131.731706,130.684827,132.041676,131.827417,132.929668,131.604474,132.918647,131.848594
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-21,106.779999,108.117422,109.904461,111.403684,109.904461,108.066971,98.834219,99.244062,100.620798,101.147591,100.605635,99.280510
2024-03-22,104.839996,107.079846,108.855903,110.848500,108.855903,107.077610,98.959043,99.380360,100.748045,101.238596,100.732930,99.396540
2024-03-25,102.629997,105.079681,106.989666,109.545084,106.989666,105.141733,99.044819,99.461635,100.869814,101.442476,100.854756,99.511543
2024-03-26,104.589996,103.051712,104.863698,108.254950,104.863698,102.944319,99.108855,99.531087,100.953262,102.275925,100.938325,99.717189
2024-03-27,NaN,105.461666,106.749172,109.555513,106.749172,105.076519,NaN,99.658931,101.016240,101.562589,101.001519,99.798491

In [124]:
m,df5=linear_model_predictions()
df5.hvplot()

[*********************100%%**********************]  1 of 1 completed

:NdOverlay   [Variable]
   :Curve   [Date]   (value)

In [ ]:
m

In [125]:
df6=feature_engineering(df5)
df6.tail()

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-03-22,106.779999,98.834219,-0.010105,6.579205,97.769049,97.404601,100.282690,98.597294,72.798125,3.338086,1.423727,1.914359,103.922563,106.576001,109.229439,4.979429,0.538440
2024-03-25,104.839996,98.959043,-0.018168,6.639403,98.352858,97.323000,100.696991,98.842105,64.959413,3.246122,1.065410,2.180711,103.951869,106.584000,109.216131,4.939073,0.168709
2024-03-26,102.629997,99.044819,-0.021080,6.525659,98.867620,97.213200,100.872719,98.990650,57.379631,2.960781,0.624056,2.336725,101.922956,106.045999,110.169043,7.775953,0.085743
2024-03-27,104.589996,99.108855,0.019098,6.457956,99.452858,97.152200,101.210653,99.210232,61.653213,2.859836,0.418488,2.441347,101.694411,105.341998,108.989585,6.925229,0.396918
2024-03-28,105.076519,99.798491,0.004652,6.296883,100.101263,97.132131,101.562095,99.440283,62.654246,2.786967,0.276496,2.510471,102.137539,104.783302,107.429065,5.049971,0.555413

In [126]:
df7=best_fit_model_future_prediction(df5)
df7.tail(1)

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2022-06-07,146.869995,153.820713,0.004514,25.135141,162.620475,185.5946,160.179922,176.504251,21.592546,-12.906143,0.387451,-13.293594,145.163814,146.729999,148.296184,2.134785,0.544693

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-03-28,105.076519,99.798491,0.004652,6.296883,100.101263,97.132131,101.562095,99.440283,62.654246,2.786967,0.276496,2.510471,102.137539,104.783302,107.429065,5.049971,0.555413

                 Close  vwap_annual
Date
2024-03-29  105.262937   100.399971

In [127]:
for i in list(range(1,25)):
    df7=best_fit_model_future_prediction(df7)
    display(df7.tail(1))

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2022-08-18,146.679993,148.53298,-0.005087,5.720709,144.425713,137.209999,144.771572,141.287619,58.34513,3.799827,-0.097741,3.897567,145.227206,149.607996,153.988785,5.856358,0.165813

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-03-29,105.262937,100.399971,0.001774,6.114456,100.727117,97.108589,101.898535,99.668622,63.05224,2.712988,0.162013,2.550975,102.575572,104.479889,106.384207,3.645329,0.705598

                 Close  vwap_annual
Date
2024-04-01  105.396877   100.923409

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2022-10-28,126.599998,136.473181,0.030945,5.007686,114.771428,119.529999,117.363436,121.032748,68.546317,1.075805,2.034364,-0.958559,115.635718,121.795999,127.95628,10.115736,0.889917

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-01,105.396877,100.923409,0.001272,5.840318,101.371731,97.061327,102.216567,99.89326,63.354418,2.634794,0.067055,2.567738,102.555152,104.591265,106.627379,3.893468,0.697831

                 Close  vwap_annual
Date
2024-04-02  105.473997   101.379892

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2023-01-11,129.119995,125.385411,0.007726,3.149958,123.465238,125.3122,124.483904,124.844434,61.775587,0.508513,1.027577,-0.519065,122.559484,126.744,130.928516,6.603099,0.783903

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-02,105.473997,101.379892,0.000732,5.435977,102.040016,97.010407,102.512697,100.112115,63.53932,2.549656,-0.014466,2.564122,104.5294,105.160065,105.790731,1.19944,0.748889

                 Close  vwap_annual
Date
2024-04-03  105.375927   101.762301

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2023-03-24,101.139999,112.695554,0.001386,3.193158,105.595714,111.9456,105.545207,111.285578,30.27894,-3.036525,-0.012111,-3.024414,99.423942,102.456,105.488057,5.91875,0.282986

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-03,105.375927,101.762301,-0.00093,5.035072,102.644108,97.195925,102.77299,100.318559,63.103281,2.446074,-0.094438,2.540512,105.041202,105.317252,105.593301,0.524225,0.606277

                 Close  vwap_annual
Date
2024-04-04  105.239088   102.012453

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2023-06-06,98.290001,107.724322,0.003164,2.523778,98.965714,101.9192,99.043093,100.659724,47.275872,-1.304348,0.142509,-1.446857,90.71547,97.278,103.84053,13.492321,0.577104

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-04,105.239088,102.012453,-0.001299,4.492058,103.249779,97.435907,102.997181,100.511211,62.459204,2.326129,-0.171507,2.497636,105.175121,105.349765,105.52441,0.331552,0.183136

                 Close  vwap_annual
Date
2024-04-05  105.125747    102.02261

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2023-08-17,101.800003,106.306692,0.010021,3.74171,106.226667,103.1122,104.298957,103.603087,41.324557,-0.538426,-0.906884,0.368458,99.485586,102.340001,105.194416,5.578297,0.40541

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-05,105.125747,102.02261,-0.001077,3.785839,103.84529,97.618822,103.190687,100.69225,61.895689,2.196604,-0.240825,2.437429,105.074123,105.322327,105.570531,0.471323,0.103995

                 Close  vwap_annual
Date
2024-04-08  105.066255   101.899601

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2023-10-27,87.519997,103.840782,-0.012747,1.717119,88.973334,96.1216,90.036454,93.787192,38.742886,-2.257509,0.444682,-2.702191,85.092237,88.256,91.419762,7.169513,0.383682

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-08,105.066255,101.899601,-0.000566,3.027343,104.377017,97.800347,103.361192,100.858048,61.581862,2.065342,-0.297664,2.363006,104.952677,105.256203,105.559729,0.576737,0.187098

                Close  vwap_annual
Date
2024-04-09  105.06571   101.698073

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-01-10,108.300003,108.601547,-0.007333,2.210079,107.060953,100.6468,106.607187,102.012855,61.926263,2.418392,-0.392277,2.810669,107.915512,108.603999,109.292487,1.267886,0.279229

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-09,105.06571,101.698073,-0.000005,1.888714,104.901574,97.974062,103.516137,100.974722,61.585575,1.939899,-0.339723,2.279622,104.936767,105.174546,105.412325,0.452161,0.271141

                 Close  vwap_annual
Date
2024-04-10  105.145736   101.384062

[*********************100%%**********************]  1 of 1 completed

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-03-22,106.779999,98.834219,-0.010105,6.579205,97.769049,97.404601,100.302352,99.444512,72.986604,3.197752,1.487489,1.710263,103.922563,106.576001,109.229439,4.979429,0.53844

,Close,vwap_annual,daily_returns,volatility_21,sma_21,sma_50,ema_21,ema_50,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0
Date,,,,,,,,,,,,,,,,,
2024-04-10,105.145736,101.384062,0.000762,1.249528,105.207562,98.161976,103.669989,101.69385,61.863207,1.772033,-0.339083,2.111116,105.00091,105.128507,105.256105,0.242746,0.567511

                 Close  vwap_annual
Date
2024-04-11  105.269513    101.13158

[*********************100%%**********************]  1 of 1 completed

Empty DataFrame
Columns: [Close, vwap_annual, daily_returns, volatility_21, sma_21, sma_50, ema_21, ema_50, RSI_14, Close, vwap_annual, daily_returns, volatility_21, sma_21, sma_50, ema_21, ema_50, BBL_5_2.0, BBM_5_2.0, BBU_5_2.0, BBB_5_2.0, BBP_5_2.0]
Index: []

[0 rows x 22 columns]

Empty DataFrame
Columns: [Close, vwap_annual, daily_returns, volatility_21, sma_21, sma_50, ema_21, ema_50, RSI_14, Close, vwap_annual, daily_returns, volatility_21, sma_21, sma_50, ema_21, ema_50, BBL_5_2.0, BBM_5_2.0, BBU_5_2.0, BBB_5_2.0, BBP_5_2.0]
Index: []

[0 rows x 22 columns]

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- MACD_12_26_9
- MACDh_12_26_9
- MACDs_12_26_9

## Predicting Stock Price for future dates

In [ ]:
#Predicting Day1
future_stock_price = best_fit_model_future_prediction(stock_predictions)
# Predicting Stocks on Future Dates _ Next 51 Days
for i in list(range(1,14)):
    future_stock_price = best_fit_model_future_prediction(future_stock_price)
    
#Display Future Stock Price Predictions
display(future_stock_price.loc[today:,:])

future_plot = future_stock_price.loc[today:,'Close'].hvplot(frame_width=500,frame_height=300)

display(future_plot)
display(model_plot*future_plot)

## Predicting Using Regressor Models

In [ ]:
# Single Target Regressor Models
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor

svr_rbf = SVR(kernel='rbf',C=100,gamma='auto')
# svr_poly = SVR(kernel='poly',C=100,degree=2, gamma='auto')

knn_uniform = KNeighborsRegressor(n_neighbors=2,weights='uniform')
knn_distance = KNeighborsRegressor(n_neighbors=5,weights='distance')

dtree = DecisionTreeRegressor(max_depth=10)

ens = MultiOutputRegressor(GradientBoostingRegressor(random_state=0))

# mlp = MLPRegressor(random_state=1, max_iter=100)

In [ ]:
# Predicting Stock Close & Volume-Weighted Average Price(VWAP) using Linear Models

def predict_regressor_close_vwap():
    # Next Day's "Close" as target
    predictors_df = technical_indicators()
    target_close_df = predictors_df[['Close']].shift(-1)
    target_vwap_df = predictors_df[['vwap_annual']].shift(-1)

    # Training Data of 27months and Testing Data of 6months alternatively 
    # with latest 33months of testing data
    train_range_months = 27
    test_range_months = 6
    split_range = list(range(len(predictors_df)//21//(train_range_months+test_range_months)))
    predictors_train = pd.DataFrame()
    
    for i in split_range:
        train_df = predictors_df.iloc[21*33*i:(21*33*i)+(21*(33-test_range_months)),:]
        predictors_train = pd.concat([predictors_train,train_df],axis=0)
        
    predictors_test = predictors_df.drop(index = predictors_train.index)
    target_train_close = target_close_df.drop(index = predictors_test.index)
    target_test_close = target_close_df.drop(index = predictors_train.index)
    target_train_vwap = target_vwap_df.drop(index = predictors_test.index)
    target_test_vwap = target_vwap_df.drop(index = predictors_train.index)
    
    #Using StandardScaler to fit predictors train data and transform both train and test data 
    predictors_scaled = scaler.fit(predictors_train)
    predictors_train_scaled = predictors_scaled.transform(predictors_train)
    predictors_test_scaled = predictors_scaled.transform(predictors_test)

    list_of_regressors = [svr_rbf,knn_uniform,knn_distance,dtree,ens]
    target_predictions_close_df = target_test_close.copy()
    for model in list_of_regressors:
        model_instance_close = model
        model_instance_close.fit(predictors_train_scaled,target_train_close)
        model_prediction_close = model_instance_close.predict(predictors_test_scaled)
        target_predictions_close_df[f'{model}_Close'] = model_prediction_close

    target_predictions_vwap_df = target_test_vwap.copy()
    for model in list_of_regressors:
        model_instance_vwap = model
        model_instance_vwap.fit(predictors_train_scaled,target_train_vwap)
        model_prediction_vwap = model_instance_vwap.predict(predictors_test_scaled)
        target_predictions_vwap_df[f'{model}_vwap_annual'] = model_prediction_vwap

    target_predictions_df = pd.concat([target_predictions_close_df,target_predictions_vwap_df],axis=1)

    display(target_predictions_df.tail())
    display(target_predictions_close_df.hvplot(frame_width=500,frame_height=300))
    return(target_predictions_close_df,target_predictions_vwap_df,target_predictions_df)

In [ ]:
# Calculating Root_Mean_Square_Error(RMSE) 
# and Mean_Absolute_Percentage_Error(MAPE)

def regressor_model_predictions():
    display(extract_stock_data(stock_name, start_date).head(3))
    display(extract_stock_data(stock_name, start_date).tail(3))
    display(technical_indicators().tail())
    today = datetime.today().strftime('%Y-%m-%d')
    target_close_predictions_df,target_vwap_predictions_df,target_predictions_df = predict_regressor_close_vwap()
    column_range_close = list(target_close_predictions_df.columns)
    column_range_vwap = list(target_vwap_predictions_df.columns)
    dict_close = {}
    dict_vwap = {}
    for i in column_range_close[1:]:
        rmse_close = np.sqrt(np.mean(
            (target_predictions_df.loc[:today,'Close']-target_predictions_df.loc[:today,i])**2))
        mape_close = np.mean(np.abs(
            (target_predictions_df.loc[:today,'Close']-target_predictions_df.loc[:today,i])/target_predictions_df.loc[:today,'Close']))*100
        dict_close[f'{i}'] = [rmse_close,mape_close]
    for i in column_range_vwap[1:]:  
        rmse_vwap = np.sqrt(np.mean(
            (target_predictions_df.loc[:today,'vwap_annual']-target_predictions_df.loc[:today,i])**2))
        mape_vwap = np.mean(np.abs(
            (target_predictions_df.loc[:today,'vwap_annual']-target_predictions_df.loc[:today,i])/target_predictions_df.loc[:today,'vwap_annual']))*100
        dict_vwap[f'{i}'] = [rmse_vwap,mape_vwap]
    error_measures_close = pd.DataFrame.from_dict(dict_close, orient = 'index', columns = ['RMSE_close','MAPE_close'])
    error_measures_vwap = pd.DataFrame.from_dict(dict_vwap, orient = 'index', columns = ['RMSE_vwap','MAPE_vwap'])
    error_measures_close = error_measures_close.sort_values(by=['MAPE_close'])
    error_measures_vwap = error_measures_vwap.sort_values(by=['MAPE_vwap'])

    display(error_measures_close)
    display(error_measures_close.hvplot.bar(rot=90,frame_width=700,frame_height=300))

    best_estimate_close = error_measures_close.index[0]
    best_estimate_vwap = error_measures_vwap.index[0]

    predictions_output = target_predictions_df[['Close','vwap_annual',best_estimate_close, best_estimate_vwap]]
    
    nxt_day = predictions_output.index[-1]+pd.Timedelta(days=1)
    #Checking for Federal Holidays
    cal = USFederalHolidayCalendar()
    holidays = pd.to_datetime(cal.holidays(today, '2024-12-31'))
    hol = list(holidays)
    for i in hol:
        if nxt_day==i:
            nxt_day = nxt_day+pd.Timedelta(days=1)
    #Checking for Weekends
    if nxt_day.weekday()==5:
        nxt_day = nxt_day+pd.Timedelta(days=2)
    elif nxt_day.weekday()==6:
        nxt_day = nxt_day+pd.Timedelta(days=1)
    else:
        nxt_day = nxt_day
    
    predictions_output.loc[nxt_day] = np.nan
    predictions_output = predictions_output.shift()
    predictions_output['Close']=predictions_output['Close'].fillna(predictions_output[best_estimate_close])
    predictions_output['vwap_annual']=predictions_output['vwap_annual'].fillna(predictions_output[best_estimate_vwap])

    predictions = predictions_output[['Close','vwap_annual']]
    best_model = best_estimate_close.removesuffix('_Close')
    comparison_plot = predictions_output[['Close',best_estimate_close]].loc['2024':today].hvplot(frame_width=300,frame_height=300)
    
    return (comparison_plot,best_model,predictions)

In [ ]:
regressor_plot,regressor,stock_predictions_regr = regressor_model_predictions()

display(stock_predictions_regr.tail())
print(f'Best fit Regressor Model: {regressor}')
regressor_plot

In [ ]:
# Creating instance of best fit regressor model
# By fitting the historical data

def best_fit_regr_future_prediction(df):
    # Next Day's "Close" as target
    predictors_df = technical_indicators()
    predictors_df = predictors_df.drop(columns=['Volume','OBV_in_million','adx_14'])
    target_close_df = predictors_df[['Close']].shift(-1)
    target_vwap_df = predictors_df[['vwap_annual']].shift(-1)

    predictors_future_df = feature_engineering(df)
    target_future_close_df = predictors_future_df[['Close']].shift(-1)
    target_future_vwap_df = predictors_future_df[['vwap_annual']].shift(-1)

    # Training Data of 27months and Testing Data of 6months alternatively 
    # with latest 33months of testing data
    train_range_months = 27
    test_range_months = 6
    split_range = list(range(len(predictors_df)//21//(train_range_months+test_range_months)))
    predictors_train = pd.DataFrame()
    
    for i in split_range:
        train_df = predictors_df.iloc[21*33*i:(21*33*i)+(21*(33-test_range_months)),:]
        predictors_train = pd.concat([predictors_train,train_df],axis=0)
        
    predictors_test = predictors_df.drop(index = predictors_train.index)
    target_train_close = target_close_df.drop(index = predictors_test.index)
    target_test_close = target_close_df.drop(index = predictors_train.index)
    target_train_vwap = target_vwap_df.drop(index = predictors_test.index)
    target_test_vwap = target_vwap_df.drop(index = predictors_train.index)
    
    #Using StandardScaler to fit predictors train data and transform both train and test data 
    predictors_scaled = scaler.fit(predictors_train)
    predictors_train_scaled = predictors_scaled.transform(predictors_train)
    predictors_future_scaled = predictors_scaled.transform(predictors_future_df)

    best_model_close = ens
    target_future_close = target_future_close_df.copy()
    model_instance_close = best_model_close
    model_instance_close.fit(predictors_train_scaled,target_train_close)
    model_prediction_close = model_instance_close.predict(predictors_future_scaled)
    target_future_close[f'{best_model_close}_Close'] = model_prediction_close

    best_model_vwap = ens
    target_future_vwap = target_future_vwap_df.copy()
    model_instance_vwap = best_model_vwap
    model_instance_vwap.fit(predictors_train_scaled,target_train_vwap)
    model_prediction_vwap = model_instance_vwap.predict(predictors_future_scaled)
    target_future_vwap[f'{best_model_vwap}_vwap_annual'] = model_prediction_vwap

    target_future_df = pd.concat([target_future_close,target_future_vwap],axis=1)

    display(target_future_df.tail(1))

    nxt_day = target_future_df.index[-1]+pd.Timedelta(days=1)
    #Checking for Federal Holidays
    cal = USFederalHolidayCalendar()
    holidays = pd.to_datetime(cal.holidays(today, '2024-12-31'))
    hol = list(holidays)
    for i in hol:
        if nxt_day==i:
            nxt_day = nxt_day+pd.Timedelta(days=1)
    #Checking for Weekends
    if nxt_day.weekday()==5:
        nxt_day = nxt_day+pd.Timedelta(days=2)
    elif nxt_day.weekday()==6:
        nxt_day = nxt_day+pd.Timedelta(days=1)
    else:
        nxt_day = nxt_day
    
    target_future_df.loc[nxt_day] = np.nan
    target_future_df = target_future_df.shift()
    target_future_df['Close']=target_future_df['Close'].fillna(target_future_df[f'{best_model_close}_Close'])
    target_future_df['vwap_annual']=target_future_df['vwap_annual'].fillna(target_future_df[f'{best_model_vwap}_vwap_annual'])

    predictions = target_future_df[['Close','vwap_annual']]
    
    return (predictions)

In [ ]:
#Predicting Day1
future_stock_price_regr = best_fit_regr_future_prediction(stock_predictions_regr)
# Predicting Stocks on Future Dates _ Next 51 Days
for i in list(range(1,14)):
    future_stock_price_regr = best_fit_regr_future_prediction(future_stock_price_regr)

#Display Regressor Model Predictions
display(future_stock_price_regr.loc[today:,:])

future_plot_regr = future_stock_price_regr.loc[today:,'Close'].hvplot(frame_width=300,frame_height=300)

display(future_plot_regr)
display(regressor_plot*future_plot_regr)

In [ ]:
regressor_plot*future_plot*future_plot_regr

In [ ]:
linear_close = future_stock_price[['Close']].rename(columns={'Close':'Close_Linear'})
regr_close = future_stock_price_regr[['Close']].rename(columns={'Close':'Close_Regr'})

combined_df = pd.concat([linear_close,regr_close],axis=1).dropna()

display(combined_df.loc[today:])

combined_df.loc[today:].hvplot()

In [ ]:

for i in list(range(1,8)):
    future_stock_price_regr=best_fit_regr_future_prediction(future_stock_price_regr)
    future_stock_price_regr

In [ ]:
future_stock_price_regr = future_stock_price_regr[['Close','vwap_annual']].dropna()

future_stock_price_regr